"""empty message

Revision ID: 03422cb90d88
Revises: 838e929ca4f7
Create Date: 2025-04-02 15:42:38.694488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03422cb90d88'
down_revision = '838e929ca4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###
