"""empty message

Revision ID: 04c10ca7899d
Revises: bad5289e19c1
Create Date: 2025-04-25 14:06:32.871462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04c10ca7899d'
down_revision = 'bad5289e19c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.drop_column('original_timezone')
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('original_timezone', mysql.VARCHAR(length=50), nullable=False))

    # ### end Alembic commands ###
