"""Fix backref naming conflict

Revision ID: 080f80557848
Revises: 1262a784cea2
Create Date: 2024-12-15 13:52:42.584335

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '080f80557848'
down_revision = '1262a784cea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_constraint('assignment_ibfk_2', type_='foreignkey')
        batch_op.drop_column('description')
        batch_op.drop_column('session_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', mysql.TEXT(), nullable=False))
        batch_op.create_foreign_key('assignment_ibfk_2', 'online_session', ['session_id'], ['id'])
        batch_op.drop_column('content')

    # ### end Alembic commands ###
