"""empty message

Revision ID: 0a40d123793d
Revises: 52a8d7acd368
Create Date: 2025-04-02 04:39:05.255046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a40d123793d'
down_revision = '52a8d7acd368'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_announcement', sa.Boolean(), nullable=True))
        batch_op.alter_column('class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.create_index('idx_message_class', ['class_id'], unique=False)
        batch_op.create_index('idx_message_recipient', ['recipient_id'], unique=False)
        batch_op.create_index('idx_message_sender', ['sender_id', 'sender_role'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key(None, 'messages', ['parent_id'], ['id'])
        batch_op.create_foreign_key(None, 'students', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index('idx_message_sender')
        batch_op.drop_index('idx_message_recipient')
        batch_op.drop_index('idx_message_class')
        batch_op.alter_column('class_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('is_announcement')
        batch_op.drop_column('is_read')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
