"""empty message

Revision ID: 0f817d12222d
Revises: 924b658c441c
Create Date: 2025-04-20 03:07:37.691937

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0f817d12222d'
down_revision = '924b658c441c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_option', sa.Integer(), nullable=True))
        batch_op.alter_column('options',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=True)
        batch_op.alter_column('correct_answer',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.String(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=1),
               nullable=False)
        batch_op.alter_column('options',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               nullable=False)
        batch_op.drop_column('correct_option')

    # ### end Alembic commands ###
