"""empty message

Revision ID: 10fe3b64b206
Revises: e87c9a99a3ed
Create Date: 2025-05-21 13:20:31.780007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fe3b64b206'
down_revision = 'e87c9a99a3ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_finalized', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('attendance_finalized')

    # ### end Alembic commands ###
