"""some changes

Revision ID: 382f80c41f53
Revises: 2508cc6d7f8c
Create Date: 2024-12-14 17:41:38.133771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '382f80c41f53'
down_revision = '2508cc6d7f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_session', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_index('room_id')
        batch_op.create_index(batch_op.f('ix_online_session_room_id'), ['room_id'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('username')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('username', ['username'], unique=True)
        batch_op.create_index('email', ['email'], unique=True)

    with op.batch_alter_table('online_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_online_session_room_id'))
        batch_op.create_index('room_id', ['room_id'], unique=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
