"""empty message

Revision ID: 38d2d43cb581
Revises: e2d436faacec
Create Date: 2025-04-04 21:13:58.658459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38d2d43cb581'
down_revision = 'e2d436faacec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('quiz_attempts_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_attempts_ibfk_2', 'users', ['student_id'], ['id'])

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
