"""empty message

Revision ID: 4513af018d67
Revises: 805129869996
Create Date: 2025-03-30 22:38:57.143214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4513af018d67'
down_revision = '805129869996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('attachment_path', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_code', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('academic_year', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('max_students', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule', sa.String(length=100), nullable=True))
        batch_op.create_index('idx_classroom_active', ['is_active'], unique=False)
        batch_op.create_index('idx_classroom_subject', ['subject_id'], unique=False)
        batch_op.create_index('idx_classroom_teacher', ['teacher_id'], unique=False)
        batch_op.create_unique_constraint(None, ['class_code'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('current_semester', sa.Integer(), nullable=True))
        batch_op.create_index('idx_student_department', ['department_id'], unique=False)
        batch_op.create_index('idx_student_name', ['first_name', 'last_name'], unique=False)
        batch_op.create_unique_constraint(None, ['student_id_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_student_name')
        batch_op.drop_index('idx_student_department')
        batch_op.drop_column('current_semester')
        batch_op.drop_column('student_id_number')

    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index('idx_classroom_teacher')
        batch_op.drop_index('idx_classroom_subject')
        batch_op.drop_index('idx_classroom_active')
        batch_op.drop_column('schedule')
        batch_op.drop_column('max_students')
        batch_op.drop_column('is_active')
        batch_op.drop_column('semester')
        batch_op.drop_column('academic_year')
        batch_op.drop_column('class_code')

    op.drop_table('class_announcements')
    # ### end Alembic commands ###
