"""Add answered_at column to quiz_answers

Revision ID: 50d8d3a76cce
Revises: e3c5669f8fc0
Create Date: 2025-05-08 19:56:20.220418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d8d3a76cce'
down_revision = 'e3c5669f8fc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_column('answered_at')

    # ### end Alembic commands ###
