"""Add face_image to User model

Revision ID: 525a81eaa9c7
Revises: 7e09f3cbcaab
Create Date: 2024-12-25 08:38:03.743642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525a81eaa9c7'
down_revision = '7e09f3cbcaab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('face_image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('face_image')

    # ### end Alembic commands ###
