"""empty message

Revision ID: 5330149b5435
Revises: a2b356e71c0a
Create Date: 2025-04-19 01:01:44.864747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5330149b5435'
down_revision = 'a2b356e71c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint('quizzes_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'teachers', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quizzes_ibfk_3', 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
