"""empty message

Revision ID: 6a66d995524a
Revises: 10fe3b64b206
Create Date: 2025-05-21 13:39:40.140179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6a66d995524a'
down_revision = '10fe3b64b206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_column('attendance_finalized')

    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_finalized', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.drop_column('attendance_finalized')

    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attendance_finalized', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
