"""empty message

Revision ID: 7ea98b7a7117
Revises: fc9795e02b06
Create Date: 2025-04-03 11:42:03.183857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7ea98b7a7117'
down_revision = 'fc9795e02b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('total_points')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_points', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('status')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('correct_option',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=False)

    # ### end Alembic commands ###
