"""empty message

Revision ID: 800f4b027702
Revises: cbb54c35aa88
Create Date: 2025-05-20 02:29:29.530415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '800f4b027702'
down_revision = 'cbb54c35aa88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answers', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_questions', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_column('total_questions')
        batch_op.drop_column('correct_answers')

    # ### end Alembic commands ###
