"""empty message

Revision ID: 838e929ca4f7
Revises: 81b423593b7c
Create Date: 2025-04-02 13:21:51.193107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '838e929ca4f7'
down_revision = '81b423593b7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enrollment_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('enrollment_date')

    # ### end Alembic commands ###
