"""empty message

Revision ID: 84887b7092f5
Revises: fee169f51612
Create Date: 2025-04-01 11:14:27.524356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84887b7092f5'
down_revision = 'fee169f51612'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'classrooms', ['classroom_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###
