"""empty message

Revision ID: 87dee03af053
Revises: 8b49db891101
Create Date: 2025-04-01 23:01:05.802104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '87dee03af053'
down_revision = '8b49db891101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('question_file_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_draft', sa.Boolean(), nullable=True))
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=150),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('max_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assignments', schema=None) as batch_op:
        batch_op.alter_column('max_score',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=150),
               existing_nullable=False)
        batch_op.drop_column('is_draft')
        batch_op.drop_column('question_file_path')
        batch_op.drop_column('questions')

    # ### end Alembic commands ###
