"""empty message

Revision ID: 939712f3a899
Revises: bb2ccd5909d3
Create Date: 2025-03-31 20:58:25.299878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939712f3a899'
down_revision = 'bb2ccd5909d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
