"""empty message

Revision ID: 960db2977644
Revises: 7d0932e22784
Create Date: 2023-08-10 12:34:56.789012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '960db2977644'
down_revision = '7d0932e22784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint('resources_ibfk_3', type_='foreignkey')
        batch_op.drop_index('idx_teacher_resource')
        batch_op.create_foreign_key(
            'resources_teacher_fk',
            'users', ['teacher_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resources', schema=None) as batch_op:
        batch_op.drop_constraint('resources_teacher_fk', type_='foreignkey')
        batch_op.create_index('idx_teacher_resource', ['teacher_id', 'resource_type'], unique=False)
        batch_op.create_foreign_key(
            'resources_ibfk_3',
            'users', ['teacher_id'], ['id']
        )
    # ### end Alembic commands ###