"""empty message

Revision ID: ae91c07e0811
Revises: 70a6c57d7b15
Create Date: 2025-04-21 03:55:16.258069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae91c07e0811'
down_revision = '70a6c57d7b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_quiz_attempt_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_quiz_attempt_user_id', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
