"""empty message

Revision ID: b367dd521c5b
Revises: d9f909641b5c
Create Date: 2025-04-24 16:16:50.378816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b367dd521c5b'
down_revision = 'd9f909641b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_message_recipient')
        batch_op.create_foreign_key(None, 'users', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index('idx_message_recipient', ['recipient_id'], unique=False)

    # ### end Alembic commands ###
