"""empty message

Revision ID: bad5289e19c1
Revises: b367dd521c5b
Create Date: 2025-04-24 19:46:05.497985

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bad5289e19c1'
down_revision = 'b367dd521c5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_modified', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('file_path',
               existing_type=mysql.VARCHAR(length=300),
               type_=sa.String(length=512),
               existing_nullable=True)
        batch_op.alter_column('score',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('submitted_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('score',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('file_path',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.drop_column('last_modified')

    # ### end Alembic commands ###
