"""empty message

Revision ID: bb2ccd5909d3
Revises: c56f26ca3f7f
Create Date: 2025-03-31 19:03:14.835566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb2ccd5909d3'
down_revision = 'c56f26ca3f7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_timezone', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.drop_column('original_timezone')

    # ### end Alembic commands ###
