"""empty message

Revision ID: c5f9859af79d
Revises: 47cda3fab80c
Create Date: 2025-04-03 14:26:33.955972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5f9859af79d'
down_revision = '47cda3fab80c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=True))
        batch_op.alter_column('correct_option',
               existing_type=mysql.VARCHAR(length=1),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('is_published')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=1),
               existing_nullable=False)
        batch_op.drop_column('position')

    # ### end Alembic commands ###
