"""empty message

Revision ID: c924ee31bd32
Revises: 38d2d43cb581
Create Date: 2025-04-04 21:20:40.052666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c924ee31bd32'
down_revision = '38d2d43cb581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('started_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
