"""empty message

Revision ID: ccf28c03062d
Revises: 939712f3a899
Create Date: 2025-03-31 21:16:15.755949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf28c03062d'
down_revision = '939712f3a899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
