"""empty message

Revision ID: d72915c421d8
Revises: 04c10ca7899d
Create Date: 2025-04-25 14:29:08.262583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72915c421d8'
down_revision = '04c10ca7899d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('online_sessions', schema=None) as batch_op:
        batch_op.drop_column('original_timezone')

    # ### end Alembic commands ###
