"""empty message

Revision ID: e8961bc09f3c
Revises: 14d2b191414e
Create Date: 2025-04-02 01:42:47.643470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8961bc09f3c'
down_revision = '14d2b191414e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_subjects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='teacher_subjects_ibfk_1'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='teacher_subjects_ibfk_2'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
