"""Add timezone to Classroom

Revision ID: ed2702ee1196
Revises: 50d8d3a76cce
Create Date: 2025-05-16 22:34:48.495305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2702ee1196'
down_revision = '50d8d3a76cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classrooms', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
